import { parseCidr } from 'cidr-tools';
import { stringifyIp } from 'ip-bigint';

import { removeNewlines, iptablesTemplate } from '#server/utils/template';
import { exec } from '#server/utils/cmd';
import { WG_ENV } from '#server/utils/config';
import {
  generatePrivateKey,
  derivePublicKey,
  generatePreSharedKey,
} from '#server/utils/wireguardKeys';
import type { ClientType } from '#db/repositories/client/types';
import type { InterfaceType } from '#db/repositories/interface/types';
import type { UserConfigType } from '#db/repositories/userConfig/types';
import type { HooksType } from '#db/repositories/hooks/types';
import {
  resolveClientAwgSettings,
  serializeAwgParameters,
} from '#server/utils/amneziawg';

type Options = {
  enableIpv6?: boolean;
};

// needed to support cli
const wgExecutable =
  typeof WG_ENV !== 'undefined' ? WG_ENV.WG_EXECUTABLE : 'dev';

export const wg = {
  generateServerPeer: (
    client: Omit<ClientType, 'createdAt' | 'updatedAt'>,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const allowedIps = [
      `${client.ipv4Address}/32`,
      ...(enableIpv6 ? [`${client.ipv6Address}/128`] : []),
      ...(client.serverAllowedIps ?? []),
    ];

    const extraLines = [];
    if (client.serverEndpoint) {
      extraLines.push(`Endpoint = ${client.serverEndpoint}`);
    }

    return `# Client: ${client.name} (${client.id})
[Peer]
PublicKey = ${client.publicKey}${client.preSharedKey ? `\nPresharedKey = ${client.preSharedKey}` : ''}
AllowedIPs = ${allowedIps.join(', ')}${extraLines.length ? `\n${extraLines.join('\n')}` : ''}`;
  },

  generateServerInterface: (
    wgInterface: InterfaceType,
    hooks: HooksType,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const cidr4 = parseCidr(wgInterface.ipv4Cidr);
    const cidr6 = parseCidr(wgInterface.ipv6Cidr);
    const ipv4Addr = stringifyIp({ number: cidr4.start + 1n, version: 4 });
    const ipv6Addr = stringifyIp({ number: cidr6.start + 1n, version: 6 });

    const address =
      `${ipv4Addr}/${cidr4.prefix}` +
      (enableIpv6 ? `, ${ipv6Addr}/${cidr6.prefix}` : '');

    let awgLines: string[] = [];

    if (wgExecutable === 'awg') {
      awgLines = serializeAwgParameters(wgInterface);
    }

    const extraLines = [...awgLines].filter((v) => v !== null);

    return `# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${wgInterface.privateKey}
Address = ${address}
ListenPort = ${wgInterface.port}
MTU = ${wgInterface.mtu}
Table = ${wgInterface.routingTable}
${extraLines.length ? `${extraLines.join('\n')}\n` : ''}
PreUp = ${iptablesTemplate(hooks.preUp, wgInterface)}
PostUp = ${iptablesTemplate(hooks.postUp, wgInterface)}
PreDown = ${iptablesTemplate(hooks.preDown, wgInterface)}
PostDown = ${iptablesTemplate(hooks.postDown, wgInterface)}`;
  },

  generateClientConfig: (
    wgInterface: InterfaceType,
    userConfig: UserConfigType,
    client: ClientType,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const address =
      `${client.ipv4Address}/32` +
      (enableIpv6 ? `, ${client.ipv6Address}/128` : '');

    const hookLines = [
      client.preUp ? `PreUp = ${removeNewlines(client.preUp)}` : null,
      client.postUp ? `PostUp = ${removeNewlines(client.postUp)}` : null,
      client.preDown ? `PreDown = ${removeNewlines(client.preDown)}` : null,
      client.postDown ? `PostDown = ${removeNewlines(client.postDown)}` : null,
    ];

    const dnsServers = client.dns ?? userConfig.defaultDns;
    const dnsLine =
      dnsServers.length > 0 ? `DNS = ${dnsServers.join(', ')}` : null;

    let awgLines: string[] = [];
    const clientAwgSettings =
      wgExecutable === 'awg'
        ? resolveClientAwgSettings(wgInterface.awgSettings, client.awgSettings)
        : null;

    if (wgExecutable === 'awg') {
      awgLines = serializeAwgParameters({
        ...wgInterface,
        jC: client.jC,
        jMin: client.jMin,
        jMax: client.jMax,
        i1: client.i1,
        i2: client.i2,
        i3: client.i3,
        i4: client.i4,
        i5: client.i5,
        awgSettings: clientAwgSettings,
      });
    }

    const extraLines = [dnsLine, ...hookLines, ...awgLines].filter(
      (v) => v !== null
    );

    return `[Interface]
PrivateKey = ${client.privateKey}
Address = ${address}
MTU = ${client.mtu}
${extraLines.length ? `${extraLines.join('\n')}\n` : ''}
[Peer]
PublicKey = ${wgInterface.publicKey}${client.preSharedKey ? `\nPresharedKey = ${client.preSharedKey}` : ''}
AllowedIPs = ${(client.allowedIps ?? userConfig.defaultAllowedIps).join(', ')}
PersistentKeepalive = ${wgExecutable === 'awg' ? (clientAwgSettings?.persistentKeepaliveRange ?? client.persistentKeepalive) : client.persistentKeepalive}
Endpoint = ${userConfig.host}:${userConfig.port}`;
  },

  generatePrivateKey: () => {
    return Promise.resolve(generatePrivateKey());
  },

  getPublicKey: (privateKey: string) => {
    return Promise.resolve(derivePublicKey(privateKey));
  },

  generatePreSharedKey: () => {
    return Promise.resolve(generatePreSharedKey());
  },

  up: (infName: string) => {
    return exec(`${wgExecutable}-quick up ${infName}`);
  },

  down: (infName: string) => {
    return exec(`${wgExecutable}-quick down ${infName}`);
  },

  restart: (infName: string) => {
    return exec(
      `${wgExecutable}-quick down ${infName}; ${wgExecutable}-quick up ${infName}`
    );
  },

  sync: (infName: string) => {
    return exec(
      `${wgExecutable} syncconf ${infName} <(${wgExecutable}-quick strip ${infName})`
    );
  },

  dump: async (infName: string) => {
    const rawDump = await exec(`${wgExecutable} show ${infName} dump`, {
      log: false,
    });

    return parseWgDump(rawDump);
  },
};

/** AWG3.1 has a longer interface row, but the eight peer columns are unchanged. */
export function parseWgDump(rawDump: string) {
  return rawDump
    .trim()
    .split('\n')
    .slice(1)
    .filter(Boolean)
    .map((line) => {
      const fields = line.split('\t');
      if (fields.length !== 8)
        throw new Error('Unexpected WireGuard peer dump');
      const [
        publicKey,
        preSharedKey,
        endpoint,
        allowedIps,
        handshake,
        rx,
        tx,
        keepalive,
      ] = fields;
      if (![handshake, rx, tx].every((value) => /^\d+$/.test(value!))) {
        throw new Error('Invalid WireGuard peer counters');
      }
      return {
        publicKey: publicKey!,
        preSharedKey: preSharedKey!,
        endpoint: endpoint === '(none)' ? null : endpoint!,
        allowedIps: allowedIps!,
        latestHandshakeAt:
          handshake === '0' ? null : new Date(Number(handshake) * 1000),
        transferRx: Number(rx),
        transferTx: Number(tx),
        persistentKeepalive: keepalive!,
      };
    });
}
